name: Build and Publish

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Install node-bindgen CLI
        run: cargo install nj-cli
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Install node-gyp and node headers (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs-dev node-gyp libssl-dev
          npm install -g node-gyp
          node-gyp install
      
      - name: Install node-gyp (Windows & Mac)
        if: matrix.os != 'ubuntu-latest'
        run: |
          npm install -g node-gyp
          node-gyp install
      
      - name: Setup additional Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          export CFLAGS="-I$(node -e 'console.log(require(\"path\").join(process.env.HOME, \".cache\", \"node-gyp\", process.versions.node, \"include\", \"node\"))')"
          export CXXFLAGS=$CFLAGS
          echo "Adding node include path: $CFLAGS"
          echo "CFLAGS=$CFLAGS" >> $GITHUB_ENV
          echo "CXXFLAGS=$CXXFLAGS" >> $GITHUB_ENV
      
      - name: Build with node-bindgen
        run: nj-cli build --release
        env:
          RUSTFLAGS: "-C link-args=-undefined dynamic_lookup"
      
      - name: Check build output
        run: |
          ls -la dist || echo "No dist directory"
          find . -name "*.node" || echo "No .node files found"
      
      - name: Create platform directory
        run: |
          mkdir -p dist/${{ matrix.platform }}
          find . -name "*.node" -exec cp {} dist/${{ matrix.platform }}/index.node \; || echo "No .node file found to copy"
      
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-binary
          path: dist/${{ matrix.platform }}/index.node

  publish:
    name: Publish Package
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Create dist directory
        run: mkdir -p dist
      
      - name: Download all platform binaries
        uses: actions/download-artifact@v3
        with:
          path: ./platform-binaries
      
      - name: Create platform directories and copy binaries
        run: |
          # Create platform-specific directories
          mkdir -p dist/linux
          mkdir -p dist/win32
          mkdir -p dist/darwin
          
          # Copy binaries to platform directories
          cp platform-binaries/linux-binary/index.node dist/linux/ || echo "No Linux binary found"
          cp platform-binaries/win32-binary/index.node dist/win32/ || echo "No Windows binary found" 
          cp platform-binaries/darwin-binary/index.node dist/darwin/ || echo "No macOS binary found"
          
          # List contents to verify
          find dist -type f
      
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}