name: Build and Publish C# Package
on:
  push:
    tags:
      - 'v*' # Trigger on version tags
      - 'cs*'
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build Rust + WASM artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build native lib for target
        run: cargo build --release --target ${{ matrix.target }}

  build-wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM with wasm-pack
        run: wasm-pack build --release --target web ./csharp-binding

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: ./pkg/*.wasm

  package:
    name: Package artifacts
    needs: [build, build-wasm]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Find relevant artifacts
        run: |
          mkdir -p release
          find target -type f \( -name "*.so" -o -name "*.dylib" -o -name "*.dll" \) -exec cp {} release/ \;
          find ./artifacts -type f -name "*.wasm" -exec cp {} release/ \;

      - name: Upload for release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
