name: Publish Rust Crate

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:

jobs:
  build-native:
    name: Build native binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build native release (gasless)
        run: cargo build --release -p gasless

      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-native-${{ matrix.os }}
          path: gasless/target/release/

  build-wasm:
    name: Build wasm binary
    runs-on: ubuntu-latest
    needs: build-native

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Build wasm release (gasless)
        run: cargo build --release --target wasm32-unknown-unknown -p gasless

      - name: Upload wasm binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-wasm-binary
          path: gasless/target/wasm32-unknown-unknown/release/

  publish-rust:
    name: Publish Rust Crate
    needs: [build-native, build-wasm]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Publish gasless crate
        working-directory: gasless
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
